/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Image;
import java.io.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;


public class ConfigWindow extends javax.swing.JFrame {

    JFileChooser fr = new JFileChooser();
    FileSystemView fw = fr.getFileSystemView();
    Base64Converter base64 = new Base64Converter();

    /**
     * Creates new form ConfigWindow
     */
    public ConfigWindow() {
        initComponents();
        load_text_fields();

        Image icon16 = new ImageIcon(getClass().getResource("img/ico/sksc_logo16.png")).getImage();
        Image icon24 = new ImageIcon(getClass().getResource("img/ico/sksc_logo24.png")).getImage();
        Image icon28 = new ImageIcon(getClass().getResource("img/ico/sksc_logo28.png")).getImage();
        Image icon30 = new ImageIcon(getClass().getResource("img/ico/sksc_logo30.png")).getImage();
        Image icon32 = new ImageIcon(getClass().getResource("img/ico/sksc_logo32.png")).getImage();
        Image icon64 = new ImageIcon(getClass().getResource("img/ico/sksc_logo64.png")).getImage();
        Image icon128 = new ImageIcon(getClass().getResource("img/ico/sksc_logo128.png")).getImage();

        List<Image> icons = new ArrayList<Image>();
        icons.add(icon16);
        icons.add(icon24);
        icons.add(icon28);
        icons.add(icon30);
        icons.add(icon32);
        icons.add(icon64);
        icons.add(icon128);

        this.setIconImages(icons);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        config_server_txt = new javax.swing.JTextField();
        config_uname_txt = new javax.swing.JTextField();
        config_db_txt = new javax.swing.JTextField();
        config_pass_txt = new javax.swing.JPasswordField();
        config_cancel_btn = new javax.swing.JButton();
        config_save_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Configuration Settings for the Database");

        jLabel2.setText("Username for the Database");

        jLabel3.setText("Password for the Database");

        jLabel4.setText("Server Name");

        jLabel5.setText("Database Name");

        config_cancel_btn.setText("Cancel");
        config_cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                config_cancel_btnActionPerformed(evt);
            }
        });

        config_save_btn.setText("Save");
        config_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                config_save_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(config_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(config_cancel_btn))
                            .addComponent(config_server_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(config_pass_txt)
                            .addComponent(config_uname_txt)
                            .addComponent(config_db_txt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(config_server_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(config_uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(config_pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(config_db_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(config_cancel_btn)
                    .addComponent(config_save_btn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void load_text_fields() {
        String line;
        try {
            base64.decode_from_base64();
            File temp_config_file = new File(fw.getDefaultDirectory() + "\\Library\\config_temp.dat");
            FileReader fr = new FileReader(temp_config_file);
            BufferedReader br = null;
            if(temp_config_file.exists()){
                br = new BufferedReader(fr);
            }
            
            while ((line = br.readLine()) != null) {
                String mysql_uname = br.readLine();
                String mysql_pass = br.readLine();
                String mysql_server = br.readLine();
                String mysql_db = br.readLine();
                config_uname_txt.setText(mysql_uname);
                config_pass_txt.setText(mysql_pass);
                config_server_txt.setText(mysql_server);
                config_db_txt.setText(mysql_db);
            }
            //fetching details from the temporary config file and delete it
            fr.close();
            br.close();
            temp_config_file.delete();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error reading the config file!");
        }
    }


    private void config_cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_config_cancel_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_config_cancel_btnActionPerformed

    private void config_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_config_save_btnActionPerformed

        if (!config_server_txt.getText().trim().equals("") && !config_uname_txt.getText().trim().equals("") && !config_db_txt.getText().trim().equals("")) {
            File file = new File("config.dat");

            File library_ms_dir = new File(fw.getDefaultDirectory() + "\\Library");

            if (!library_ms_dir.exists()) {
                try {
                    library_ms_dir.mkdir();
                } catch (SecurityException ex) {
                    JOptionPane.showMessageDialog(null, "Cannot create a folder in your document, because of security of your system");
                }
            }

            try {
                FileOutputStream writeStream = new FileOutputStream(file, false); // true to append
                PrintWriter pw = new PrintWriter(writeStream);
                pw.println("");
                pw.println(config_uname_txt.getText().trim());
                pw.println(config_pass_txt.getText().trim());
                pw.println(config_server_txt.getText().trim());
                pw.println(config_db_txt.getText().trim());
                pw.flush();
                pw.close();

                base64.encode_to_base64(); //convert temporary file to Base64
                file.delete(); //delete temporary created file
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error writting to config file!");
            }

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Server name, Username and Database fields are required!");
        }

    }//GEN-LAST:event_config_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigWindow().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton config_cancel_btn;
    private javax.swing.JTextField config_db_txt;
    private javax.swing.JPasswordField config_pass_txt;
    private javax.swing.JButton config_save_btn;
    private javax.swing.JTextField config_server_txt;
    private javax.swing.JTextField config_uname_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
